### ISSUE TITLE
Add callback registration for torque feedback message

### ISSUE THREAD

**Issue by maxipalay** [odriverobotics/ODriveArduino#5]
Hey,

As I was working on a project using the ODriveArduino library and I needed torque feedback from the ODrives, I added the option to register a callback for handling torque estimates messages. I have this working successfully in my project. Are you guys interested and/or is it an option to make a PR to integrate this?

**Comment by samuelsadok** [comment]
That sounds like a useful addition. I guess it will be similar to the existing way of getting encoder feedback? Happy to look at a PR if you wanna open one. Might make sense to rename the existing function and callback (but keeping the old function name as alias for backwards compatibility).

**Comment by maxipalay** [comment]
Yes, it's just basically adding a case to the switch statement for the processing of the incoming messages and a way to register a callback for a received message of the type torque estimates. I didn't change the names of any previous functions, just added on top of it. e.g. onFeedback -> registers a callback for encoder estimates, onTorques -> registers a callback for torque estimates. 

I'd be happy to make these small modifications and contribute, I'll make a PR and we can talk on it.

**Comment by samuelsadok** [comment]
Addressed by #6
